### ISSUE TITLE
Emoji in Stack Trace?

### ISSUE THREAD

**Issue by abernix** [xolvio/meteor-jasmine#287]
For some reason when I add `sanjo:jasmine`, I suddenly get fun little Emoji icons in my Stack Traces with  `meteor://` file path prefixes.  Is this by design?

I really don't mind, it's just a bit confusing.  :computer: :smile_cat:  :computer:

**Without `sanjo:jasmine`**
```
W20151001-15:01:09.719(3)? (STDERR) Error: MyThrownError
W20151001-15:01:09.719(3)? (STDERR)     at server/lib/test.js:3:7
```

**With `sanjo:jasmine`**
```
W20151001-15:00:48.565(3)? (STDERR) Error: MyThrownError
W20151001-15:00:48.566(3)? (STDERR)     at meteor://💻app/server/lib/test.js:3:7
```

**Comment by Sanjo** [comment]
It's a bug since Meteor 1.2. I will look into this, this week.

**Comment by abernix** [comment]
I think this can be closed unless you want to look further.  It (strangely, now I can't reproduce anymore) only happened when I added `sanjo:jasmine` and went away when I removed it, but it looks like it's related to something Meteor intended meteor/meteor#5342

**Comment by abernix** [comment]
Ok, j/k – I *can* reproduce it, but it's more specific to `velocity:core` and `velocity:source-map-support`.  (I noticed this initially on `sanjo:jasmine` because I had removed `xolvio:cucumber` yesterday) 

Normally the emoji only shows up in the "Sources" of Chrome Dev Tools, but once `velocity:core` is installed, the magical emoji moves into the stack traces themselves on both client and server.

Ultimately though, this happened because of whatever Meteor did in 1.2... [here's the code where it's getting added by Meteor](https://github.com/meteor/meteor/blob/7191dfcf3e4a134adcca6c7fc5ac33b45d619493/tools/isobuild/bundler.js#L918).

Anyhow, hope this helps.
