### ISSUE TITLE
ReferenceError: ComponentMocker is not defined

### ISSUE THREAD

**Issue by dasdeck** [xolvio/meteor-jasmine#310]
Hey!
Out of th ebox i get the following error:

`````
/Users/jms/.meteor/packages/velocity_meteor-tool/.1.1.10_2.zq4oe9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
ReferenceError: ComponentMocker is not defined
    at meteor://ðŸ’»app/tests/jasmine/server/integration/package-stubs.js:12922:40
    at /Users/jms/meteor/jobs/.meteor/local/mirrors/jasmine-server-integration/.meteor/local/build/programs/server/app/tests/jasmine/server/integration/package-stubs.js:12935:4
    at /Users/jms/meteor/jobs/.meteor/local/mirrors/jasmine-server-integration/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/jms/.meteor/packages/velocity_meteor-tool/.1.1.10_2.zq4oe9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/jms/meteor/jobs/.meteor/local/mirrors/jasmine-server-integration/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
`````

any ideas?

Cheers!

JM

edit:

After removeing all the "stub" code, the mirror runs smoothly.
I guess this will rob me of some functionality in the future thougth?

**Comment by Sanjo** [comment]
ComponentMocker is something that I just used for the (not recommended) server unit mode. Jasmine has built in tools for stubbing. Just use those. http://jasmine.github.io/2.3/introduction.html#section-Spies
